[package]
name = "meziantou_music_app_webplayer_desktop"
version = "1.0.0"
description = "Meziantou Music App desktop wrapper"
authors = ["meziantou"]
license = "MIT"
repository = "https://github.com/meziantou/Meziantou.MusicApp"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "meziantou_music_app_webplayer_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.11.0", features = [] }
