<Project Sdk="Meziantou.NET.Sdk.Test">

  <ItemGroup>
    <PackageReference Include="Meziantou.Extensions.Logging.InMemory" Version="2.0.6" />
    <PackageReference Include="Meziantou.Extensions.Logging.Xunit.v3" Version="3.0.6" />
    <PackageReference Include="Meziantou.Framework.InlineSnapshotTesting" Version="6.0.8" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="3.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meziantou.MusicApp.Server\Meziantou.MusicApp.Server.csproj" />
  </ItemGroup>

</Project>
